FROM golang:1.24 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o todo-app ./cmd/web/

FROM gcr.io/distroless/static:nonroot

WORKDIR /app
COPY --from=builder /app/todo-app .
COPY --from=builder /app/static ./static

USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/app/todo-app"]
