FROM golang:1.24 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o todo-dbworker ./cmd/db-handler/

FROM gcr.io/distroless/static:nonroot

WORKDIR /app
COPY --from=builder /app/todo-dbworker .

USER nonroot:nonroot
ENTRYPOINT ["/app/todo-dbworker"]
